### ISSUE TITLE
missing warning when pasting more than x allowed chars into empty editor

### ISSUE THREAD

**Issue by brunis** [w8tcha/CKEditor-WordCount-Plugin#192] opened 2019-09-28 04:51 UTC
Pasting eg. >16000 chars into an editor where wordcount is set to have a max of 16000 chars including counting whitespace, htmlchars, does not trigger max. charcount or pastewarning.
It works if I have a single short paragraph in there.

**Comment by w8tcha** [comment] 2019-10-13 03:03
Are you using the latest version? atleast with ckeditor 4.13.0 and wordcount 1.17.6 i cannot reproduce the isssue

**Comment by brunis** [comment] 2019-11-11 11:21
I think it might be related to rich text pasted from other editors. Seems WordCount kicks in before any CKEditor filtering.. so fx. from Word you can paste about 10k "chars", but still hit the 16k limit. Will you confirm your counter is after any filtering, etc.?  no need to count before.

**Comment by brunis** [comment] 2019-11-11 11:29
There is also a difference in the way the plugin alerts about errors, if you try to paste past the char limit, it shows differently when the document is empty and when it already has text. I can open a different bug?

**Comment by w8tcha** [comment] 2019-11-15 14:26
>  I can open a different bug?

Yes, sure!

**Comment by w8tcha** [comment] 2019-11-15 14:27
> Will you confirm your counter is after any filtering, etc.? no need to count before.

Looks like there is a special event for paste from word. I will implement this in the next release!

**Comment by w8tcha** [comment] 2019-11-15 14:33
I comitted a fix for this issue!

**Closed** 2019-11-15 14:32 UTC
